version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: go-mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devbook
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
  
  adminer:
    image: adminer
    container_name: go-adminer
    restart: always
    ports:
      - 8080:8080